# Generated by Django 4.0.5 on 2022-06-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='aircraft_code')),
                ('range_of', models.IntegerField(verbose_name='range')),
                ('model', models.CharField(max_length=20, verbose_name='model')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='airport_code')),
                ('airport_name', models.CharField(max_length=30, verbose_name='airport_name')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('longitude', models.CharField(max_length=20, verbose_name='longitude')),
                ('latitude', models.CharField(max_length=20, verbose_name='latitude')),
                ('timezone', models.DateTimeField(verbose_name='timezone')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='book_ref')),
                ('book_data', models.DateTimeField(verbose_name='book_data')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='total_amount')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='flight_id')),
                ('flight_no', models.IntegerField(verbose_name='flight_no')),
                ('scheduled_departure', models.DateTimeField(verbose_name='scheduled_departure')),
                ('departure_airport', models.CharField(max_length=30, verbose_name='departure_airport')),
                ('arrival_airport', models.CharField(max_length=30, verbose_name='arrival_airport')),
                ('actual_departure', models.DateTimeField(verbose_name='actual_departure')),
                ('actual_arrival', models.DateTimeField(verbose_name='actual_arrival')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.aircraft', verbose_name='aircraft_code')),
                ('airport_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.airport', verbose_name='airport_code')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ticket_no')),
                ('passenger_id', models.IntegerField(verbose_name='passenger_id')),
                ('passenger_name', models.CharField(max_length=20, verbose_name='passenger_name')),
                ('contact_data', models.CharField(max_length=20, verbose_name='contact_data')),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.booking', verbose_name='book_ref')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'Hight')], verbose_name='fare_conditions')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='amount')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.flight', verbose_name='flight_id')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.ticket', verbose_name='ticket_no')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seats_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='seats_no')),
                ('fare_conditions', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'Hight')], verbose_name='fare_conditions')),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.aircraft', verbose_name='aircraft_code')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField(verbose_name='flight_id')),
                ('boarding_no', models.IntegerField(verbose_name='boarding_no')),
                ('seat_no', models.IntegerField(verbose_name='seat_no')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aero.ticket', verbose_name='ticket_no')),
            ],
            options={
                'verbose_name': 'BoardingPass',
                'verbose_name_plural': 'BoardingPasses',
            },
        ),
    ]
